# Generated by Django 3.1.3 on 2020-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=25)),
                ('org_serial_code', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'UnAssigned'), ('lost', 'Lost'), ('lost & found', 'Lost and Found')], default='assigned', max_length=50)),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.TextField()),
            ],
        ),
    ]
